# Computation on Arrays: Broadcasting

또 다른 *vectorize* operation의 예는 NumPy *broadcasting* 기능을 이용하는 것이다.
Broadcasting 은 서로 다른 크기의 array의 연산이 가능하도록 하는 다음 몇 가지 규칙을 말한다. 

## Rules of Broadcasting

임의의 두 array에 대해 다음과 같은 규칙이 적용된다. 

- Rule 1: 두 array의 차원 수가 다를 경우 낮은 차원 수의 array에서 부족한 차원 개수만큼 왼쪽에 1을 집어넣어 차원수를 맞춘다. 
- Rule 2: 각 차원에서 그 크기가 다른 경우 차원값이 1인 것을 변경하여 일치시킨다. 
- Rule 3: Rule 2가 적용되지 않는다면 오류를 발생시킨다. 

In [ ]:
import numpy as np

### Broadcasting example 1


In [ ]:
M = np.ones((2, 3))
a = np.arange(3)

두 array의 shape는 다음과 같다. 

- ``M.shape = (2, 3)``
- ``a.shape = (3,)``

Rule 1에 의해, 

- ``M.shape -> (2, 3)``
- ``a.shape -> (1, 3)``

Rule 2에 의해, 

- ``M.shape -> (2, 3)``
- ``a.shape -> (2, 3)``

따라서 다음과 같이 계산된다. 

In [ ]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

### Broadcasting example 2


In [ ]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

두 array의 shape는 다음과 같다.

- ``a.shape = (3, 1)``
- ``b.shape = (3,)``

Rule 1 에 의해,

- ``a.shape -> (3, 1)``
- ``b.shape -> (1, 3)``

Rule 2 에 의해,

- ``a.shape -> (3, 3)``
- ``b.shape -> (3, 3)``

따라서 다음과 같이 계산된다.

In [ ]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Broadcasting example 3


In [ ]:
M = np.ones((3, 2))
a = np.arange(3)

두 array의 shape는 다음과 같다.

- ``M.shape = (3, 2)``
- ``a.shape = (3,)``

Rule 1 에 의해,

- ``M.shape -> (3, 2)``
- ``a.shape -> (1, 3)``

Rule 2 에 의해,

- ``M.shape -> (3, 2)``
- ``a.shape -> (3, 3)``

Rule 3 에 의해 오류가 발생한다.

In [ ]:
M + a

ValueError: ignored

## Broadcasting in Practice

### Centering an array

In [ ]:
X = np.random.random((10, 3))

In [ ]:
Xmean = X.mean(0)
Xmean

array([0.58503913, 0.38444013, 0.57348045])

In [ ]:
X_centered = X - Xmean

``X_centered``의 shape와 결과를 생각해 보자.