# Comparisons, Masks, and Boolean Logic

Boolean opeartion은 predicate logic을 다루는 데 필요하다. NumPy에서 어떻게 사용하는지 알아보자. 

## Comparison Operators as ufuncs

다음 비교문을 살펴 보자.

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [3]:
x < 3  # less than

array([ True,  True, False, False, False])

In [4]:
x > 3  # greater than

array([False, False, False,  True,  True])

In [5]:
x <= 3  # less than or equal

array([ True,  True,  True, False, False])

In [6]:
x >= 3  # greater than or equal

array([False, False,  True,  True,  True])

In [7]:
x != 3  # not equal

array([ True,  True, False,  True,  True])

In [8]:
x == 3  # equal

array([False, False,  True, False, False])

In [9]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

산술연산자와 마찬가지로 비교 operator는 NumPy의 실제 구현 함수의 wrapper이다. 

| Operator	    | Equivalent ufunc    || Operator	   | Equivalent ufunc    |
|---------------|---------------------||---------------|---------------------|
|``==``         |``np.equal``         ||``!=``         |``np.not_equal``     |
|``<``          |``np.less``          ||``<=``         |``np.less_equal``    |
|``>``          |``np.greater``       ||``>=``         |``np.greater_equal`` |

In [40]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [11]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

## Working with Boolean Arrays



In [12]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


### Counting entries

Boolean array에서 ``True`` 개수를 헤아려 보자. 

In [13]:
x<6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [14]:
# how many values less than 6?
np.count_nonzero(x < 6)

8

사실 아래와 같이 계산할 수도 있다.

이 때,  ``False`` 는  ``0``,  ``True`` 는  ``1``로 해석됨에 주의하자.

In [15]:
np.sum(x < 6)

8

``sum()``을 사용하면 좋은 이유 중 하나는 row 및 column별 계산이 가능하다는 점이다. 

In [16]:
x<6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [17]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

array([4, 2, 2])

array의 적어도 하나의 원소가, 혹은 모든 원소가 predicate을 만족하는지를 조사할 때  ``np.any`` 와  ``np.all``을 사용할 수 있다.

In [18]:
# are there any values greater than 8?
np.any(x > 8)

True

In [19]:
# are there any values less than zero?
np.any(x < 0)

False

In [20]:
# are all values less than 10?
np.all(x < 10)

True

In [21]:
# are all values equal to 6?
np.all(x == 6)

False

sum method처럼 ``np.all`` 과 ``np.any``도 axis를 지정할 수 있다. 

In [22]:
# are all values in each row less than 8?
np.all(x < 8, axis=1)

array([ True, False,  True])

### Boolean operators

 *bitwise logic operators* 용법도 고려하자.
 
 ``&``, ``|``, ``^``,  ``~``.


In [23]:
x>1

array([[ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [24]:
x<5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [25]:
(x > 1) & (x < 5)

array([[False, False,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [26]:
np.sum((x > 1) & (x < 5))

5

마찬가지로 NumPy의 함수는 다음과 같다.

| Operator	    | Equivalent ufunc    || Operator	    | Equivalent ufunc    |
|---------------|---------------------||---------------|---------------------|
|``&``          |``np.bitwise_and``   ||&#124;         |``np.bitwise_or``    |
|``^``          |``np.bitwise_xor``   ||``~``          |``np.bitwise_not``   |

## Boolean Arrays as Masks

Boolean array를 통해 mask 기능을 구현할 수 있다.

In [27]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [28]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [29]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])

## Aside: Using the Keywords and/or Versus the Operators &/|

``and`` and ``or``vs. ``&`` and ``|`` 

- ``and`` and ``or`` : the truth or falsehood of *entire object*
- ``&`` and ``|`` :  *bits within each object*.



In [30]:
bool(42), bool(0)

(True, False)

In [31]:
bool(42 and 0)

False

In [32]:
bool(42 or 0)

True

In [33]:
bin(42)

'0b101010'

In [34]:
bin(59)

'0b111011'

In [35]:
bin(42 & 59)

'0b101010'

In [36]:
bin(42 | 59)

'0b111011'

In [37]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

array([ True,  True,  True, False,  True,  True])

다음과 같이 사용할 수 없음에 주의하자.

In [38]:
A or B

ValueError: ignored